# Generated by Django 5.0.2 on 2024-02-28 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('lang_id', models.IntegerField(blank=True, null=True)),
                ('chat_id', models.BigIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=150)),
                ('name_ru', models.CharField(max_length=150)),
                ('name_en', models.CharField(blank=True, max_length=150, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_battles', to='bot_app.battle')),
            ],
            options={
                'verbose_name_plural': 'Battles',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=150)),
                ('name_ru', models.CharField(max_length=150)),
                ('name_en', models.CharField(blank=True, max_length=150, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='bot_app.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('answer_a', models.CharField(default='Default Answer A', max_length=255)),
                ('answer_b', models.CharField(default='Default Answer B', max_length=255)),
                ('answer_c', models.CharField(default='Default Answer C', max_length=255)),
                ('answer_d', models.CharField(default='Default Answer D', max_length=255)),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='uploads/tests/')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='bot_app.battle')),
            ],
        ),
    ]
