# Generated by Django 5.0.2 on 2024-02-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to='uploads/excel/')),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_a',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_b',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_c',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='answer_d',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
