# Generated by Django 5.0.2 on 2024-03-16 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0002_excelupload_alter_test_answer_a_alter_test_answer_b_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcelUpload',
        ),
    ]
