# Generated by Django 5.0.2 on 2024-04-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0003_delete_excelupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='categoriya',
            field=models.CharField(default='some_default_value', max_length=100),
        ),
    ]
