# Generated by Django 5.0.2 on 2024-04-30 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0004_test_categoriya'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='categoriya',
        ),
        migrations.AddField(
            model_name='test',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bot_app.category'),
        ),
    ]
