# Generated by Django 5.0.2 on 2024-04-30 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0005_remove_test_categoriya_test_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='battle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_app.battle'),
        ),
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_app.category'),
        ),
    ]
