# Generated by Django 5.0.2 on 2024-05-04 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0006_alter_test_battle_alter_test_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to='bot_app.user')),
            ],
            options={
                'verbose_name_plural': 'Admins',
            },
        ),
    ]
