# Generated by Django 5.0.2 on 2024-05-31 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0009_alter_admin_options_alter_admin_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=150)),
                ('quiz_id', models.CharField(max_length=150)),
                ('unique_id', models.CharField(editable=False, max_length=150, unique=True)),
                ('quiz_number', models.CharField(max_length=150)),
                ('quiz_time', models.CharField(max_length=150)),
                ('created_at', models.CharField(default='', editable=False, max_length=150)),
                ('updated_at', models.CharField(default='', editable=False, max_length=150)),
            ],
        ),
    ]
