# Generated by Django 5.0.2 on 2024-05-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0011_remove_history_updated_at_history_formatted_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='formatted_time',
        ),
        migrations.AlterField(
            model_name='history',
            name='created_at',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
