# Generated by Django 5.0.2 on 2024-06-08 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0015_alter_results_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_app.user')),
            ],
            options={
                'verbose_name_plural': 'Set Admins',
            },
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
