# Generated by Django 5.0.2 on 2024-06-08 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0016_setadmin_delete_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setadmin',
            name='is_active',
        ),
    ]
