# Generated by Django 5.0.2 on 2024-06-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0017_remove_setadmin_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
