# Generated by Django 5.0.2 on 2024-06-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0018_remove_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetBio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uz_text', models.TextField(blank=True, null=True, verbose_name='Uzbek Text')),
                ('ru_text', models.TextField(blank=True, null=True, verbose_name='Russian Text')),
            ],
            options={
                'verbose_name_plural': 'Set about',
            },
        ),
    ]
